#!/usr/bin/env sh

NVDSRC="${NVDSRC:-/usr/src/nvidia-drivers}"
[ -e "${0}.disabled" ] && exit 0
which make >/dev/null 2>&1 || exit 0
[ -d "${NVDSRC}" ] || exit 0
V="${1:-`uname -r`}"

echo "Build NVIDIA module..." >&2
cd "${NVDSRC}"
exec make module-install PWD="${NVDSRC}"
