#!/usr/bin/env sh

run() {
	echo "$*"
	exec "$@"
}

[ -e "${0}.disabled" ] && exit 0
which make >/dev/null 2>&1 || exit 0

NVDSRC="${NVDSRC:-/usr/src/nvidia-drivers}"
[ -d "${NVDSRC}" ] || exit 0

V="${1:-`uname -r`}"
SYSSRC="/lib/modules/${V}/source"
SYSOUT="/lib/modules/${V}/build"

echo "Build NVIDIA module..." >&2
cd "${NVDSRC}"
run make module-install SYSSRC="${SYSSRC}" KBUILD_OUTPUT="${SYSOUT}" PWD="${NVDSRC}"
